# Class: oumi.core.configs.InferenceConfig
# https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py

# Note, if you are running on a multi-GPU machine, constraint the execution
# to a single GPU, e.g., `export CUDA_VISIBLE_DEVICES=0`

model:
  model_name: "Qwen/Qwen2-VL-2B-Instruct"
  torch_dtype_str: "bfloat16"
  model_max_length: 4096
  chat_template: "qwen2-vl-instruct"
  trust_remote_code: True

generation:
  max_new_tokens: 64
  batch_size: 1

engine: NATIVE
